module.exports = [
    { 'uf': 'Acre' },
    { 'uf': 'Alagoas' },
    { 'uf': 'Amapá' },
    { 'uf': 'Amazonas' },
    { 'uf': 'Bahia' },
    { 'uf': 'Ceará' },
    { 'uf': 'Distrito Federal' },
    { 'uf': 'Espírito Santo' },
    { 'uf': 'Goías' },
    { 'uf': 'Maranhão' },
    { 'uf': 'Mato Grosso' },
    { 'uf': 'Mato Grosso do Sul' },
    { 'uf': 'Minas Gerais' },
    { 'uf': 'Pará' },
    { 'uf': 'Paraíba' },
    { 'uf': 'Paraná' },
    { 'uf': 'Pernambuco' },
    { 'uf': 'Piauí' },
    { 'uf': 'Rio de Janeiro' },
    { 'uf': 'Rio Grande do Norte' },
    { 'uf': 'Rio Grande do Sul' },
    { 'uf': 'Rondônia' },
    { 'uf': 'Roraíma' },
    { 'uf': 'Santa Catarina' },
    { 'uf': 'São Paulo' },
    { 'uf': 'Sergipe' },
    { 'uf': 'Tocantins' },
  ]